_wandb:
    value:
        cli_version: 0.21.3
        e:
            qjgw0zzcuda2w6yfh5io2qy4u7ujllub:
                args:
                    - --object_code
                    - s20349
                    - --output_dir
                    - ./visualizations
                codePath: grasp_generation/scripts/affordance_aligned_optimization.py
                codePathLocal: scripts/affordance_aligned_optimization.py
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "948419567616"
                        used: "270980046848"
                email: eunha010724@gmail.com
                executable: /home/dmsgk724/anaconda3/envs/dexgys/bin/python
                git:
                    commit: bd1b13d7248729af117e1d46aaa6266b147a3c7b
                    remote: https://github.com/PKU-EPIC/DexGraspNet.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-14056924-4265-34f3-3e3a-2b165569a27c
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-00132c99-7d5a-2536-ef00-8a86f83bf9f9
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-67d5c448-b8b8-d28c-2bb3-634c5116add6
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-cced02fe-ecf1-c461-dba6-44c48996a4c4
                host: cho2node32
                memory:
                    total: "270108524544"
                os: Linux-5.15.0-86-generic-x86_64-with-glibc2.17
                program: scripts/affordance_aligned_optimization.py
                python: CPython 3.8.20
                root: /home/dmsgk724/CVPR_2026/grasping/DexGraspNet/grasp_generation
                startedAt: "2025-10-11T12:41:53.691207Z"
                writerId: qjgw0zzcuda2w6yfh5io2qy4u7ujllub
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 53
                - 105
            "2":
                - 1
                - 5
                - 53
                - 105
            "3":
                - 2
                - 13
                - 16
            "4": 3.8.20
            "5": 0.21.3
            "12": 0.21.3
            "13": linux-x86_64
data_path:
    value: /home/dmsgk724/CVPR_2026/dataset/processed_dexgys3/s20349/xyzc.npy
device:
    value: cuda
grasp_idx:
    value: 0
mesh_data_path:
    value: /home/dmsgk724/CVPR_2026/grasping/Grasp-as-You-Say/asset_process/data/meshdata
num_steps:
    value: 1000
object_code:
    value: s20349
w_bar:
    value: 1
w_dir:
    value: 10
w_dis:
    value: 100
w_fc:
    value: 1
